### ISSUE TITLE
Access token `kaskada-ai-antora` about to expire 

### ISSUE THREAD

**Issue by therapon** [kaskada-ai/docs-site#22]
Hi, 

 I have a personal access token `kaskada-ai-antora` that is about to expire. I believe is used in one of the antora related repos for kaskada but I no longer have access to check/verify. 

 If we could verify that it is still in use then could we replace it with something owned by the kaskada org? 

 Let me know if there is anything on my end that needs to be done for this and I'll make sure it gets done.

**Comment by bjchambers** [comment]
It should be OK to let the token expire. It shouldn't be in use anymore and I didn't see any place it was in use. If anything breaks after it expires we can take a look at fixing it.
